let local = {
  en: {
    api: {
      "Unknown Error": "An unknown error occurred",
    },
    index: {
      "Current Items": "Current Items",
      "Total Items": "Total Items",
      "Search": "Search",
      "Search-By": "Search by item name...",
      filter: {
        "All Items": "All Items",
        "Expired Items": "Expired Items",
        "Expiring Soon": "Expiring Soon",
        "Room Type": "Room Type",
      },
      sortBy: {
        "None": "None",
        "Price-ExpToCheap": "Price: Expensive to Cheapest",
        "Price-CheapToExp": "Price: Cheapest to Expensive",
        "Expiry-NearFirst": "Expiry Date: Nearest First",
        "Expiry-FarFirst": "Expiry Date: Farthest First",
      },
    },
    info: {
      "Inventory Statistics": "Inventory Statistics",
      "Key Summary": "Key Summary",
      "Total Value": "Total Value",
      "Unique Items": "Unique Items",
      "Expiring Soon": "Expiring Soon",
      "Expired Items": "Expired Items",
      "Expiration Warning": "Expiration Warning",
      "Expired Notice": "You have {{value}} kr worth of expired items!",
      "Expiring Soon Notice":
        "You have {{value}} kr worth of expiring soon items!",
      "View": "View",
    },
    additem: {
      "Add Item": "Add Item",
      "Name": "Name",
      "Price": "Price",
      "Measurement Amount": "Measurement Amount",
      "Measurement Type": "Measurement Type",
      "Room Name": "Room Name",
      "Room Type": "Room Type",
      "Expiry Date": "Expiry Date",
      "Amount of Items": "Amount of Items",
      "Save": "Save",
      "Failed-Save-Item": "Failed to save the item. Please try again",
      "Success-Save-Item": "The new item has been saved succesfully",
      "Missing Information": "Make sure all fields are filled in",
      "Select ": "Select ",
    },
    item: {
      Amount: "Amount",
      "Added in": "Added in",
      "Price Per Item": "Price Per Item",
      "Expires in": "Expires in",
      "Found in": "Found in",
      "Update Amount": "Update Amount",
      "Price-Not-Provided": "Price not provided",
      "Save": "Save",
    },
  },
  hr: {
    api: {
      "Unknown Error": "Došlo je do nepoznate pogreške",
    },
    index: {
      "Current Items": "Trenutačne stavke",
      "Total Items": "Ukupno stavki",
      "Search": "Pretraživanje",
      "Search-By": "Pretraži po nazivu stavke...",
      filter: {
        "All Items": "Sve stavke",
        "Expired Items": "Istekle stavke",
        "Expiring Soon": "Uskoro ističe",
        "Room Type": "Tip sobe",
      },
      sortBy: {
        "None": "Nijedan",
        "Price-ExpToCheap": "Cijena: Od skupih do najjeftinijih",
        "Price-CheapToExp": "Cijena: Od najjeftinije do najskuplje",
        "Expiry-NearFirst": "Datum isteka: Najbliži prvi",
        "Expiry-FarFirst": "Datum isteka: Prvo najdalje",
      },
    },
    info: {
      "Inventory Statistics": "Statistika inventara",
      "Key Summary": "Ključni sažetak",
      "Total Value": "Ukupna vrijednost",
      "Unique Items": "Unikatni predmeti",
      "Expiring Soon": "Uskoro ističe",
      "Expired Items": "Istekle stavke",
      "Expiration Warning": "Upozorenje o isteku",
      "Expired Notice":
        "Imate isteklih artikala u vrijednosti od {{value}} kr!",
      "Expiring Soon Notice":
        "Imate artikle u vrijednosti od {{value}} kr koji uskoro istječu!",
      "View": "Pogled",
    },
    additem: {
      "Add Item": "Dodaj stavku",
      "Name": "Ime",
      "Price": "Cijena",
      "Measurement Amount": "Iznos mjerenja",
      "Measurement Type": "Vrsta mjerenja",
      "Room Name": "Naziv sobe",
      "Room Type": "Tip sobe",
      "Expiry Date": "Datum isteka",
      "Amount of Items": "Količina stavki",
      "Save": "sačuvaj",
      "Failed-Save-Item": "Spremanje stavke nije uspjelo. Pokušajte ponovno.",
      "Success-Save-Item": "Nova stavka je uspješno spremljena",
      "Missing Information": "Provjerite jesu li sva polja ispunjena",
      "Select ": "Odaberite ",
    },
    item: {
      "Amount": "Iznos",
      "Added in": "Dodano u",
      "Price Per Item": "Cijena po artiklu",
      "Expires in": "Istječe za",
      "Found in": "Pronađeno u",
      "Update Amount": "Dodaj iznos",
      "Price-Not-Provided": "Cijena nije navedena",
      "Save": "sačuvaj",
    },
  },
};
export default local;
